### ISSUE TITLE
[product_unique_serial]: Serial numbers doesn't show when transfering

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/stock-logistics-workflow#15]
### Impacted versions:
- 8.0
### Steps to reproduce:
- Make sure you have at least one serial number defined for a product (Let's say **iPad Mini** with **mini6** as serial number)
- Create a picking
- Click on 'Mark as Todo'
- Click on 'Transfer' (let the wizard pop up)
### Current behavior:
- When trying to select Serial/Lot number **mini6** in **Lot** column, it won't let you select it

> ![image](https://cloud.githubusercontent.com/assets/2961943/16279641/b9008070-3885-11e6-8f38-ff8be4640390.png)
- Picking cannot be done

> Console's output is giving the following

`2016-06-30 00:13:23,863 1823 WARNING openerp_test openerp.osv.expression: The domain term '('quant_ids', '=', [])' should use the 'in' or 'not in' operator.`
### Expected behavior:
- Select **mini6** from all availables Serial/Lot numbers

> ![image](https://cloud.githubusercontent.com/assets/2961943/16279638/b4f3f106-3885-11e6-92be-5e6570f626ce.png)
- Do picking transfer successfully
### Video/Screenshot link (optional):

> [Video](https://drive.google.com/a/vauxoo.com/file/d/0BzqRx_KjnyMQMi1lUWx4dGEzYUk/view?usp=sharing)

**Comment by osvalr** [comment]
Hi @suniagajose @gquilarque @JulioSerna , have you guys seen this?

**Comment by suniagajose** [comment]
Hi @osvalr 

maybe function [_get_last_location_id](https://github.com/Vauxoo/stock-logistics-workflow/blob/8.0/product_unique_serial/model/stock.py#L30) is not working properly? do you see if field last_location_id is not false for the serial(s) number(s) that you expected?

**Comment by JulioSerna** [comment]
@osvalr 

Before transfer the picking should be reserved, and when is reserved there are quants related, could you check and send one image with that information?

**Comment by osvalr** [comment]
Hi @JulioSerna please see the following [video](https://drive.google.com/a/vauxoo.com/file/d/0BzqRx_KjnyMQMi1lUWx4dGEzYUk/view?usp=sharing)

**Comment by osvalr** [comment]
HI @suniagajose `last_location_id` is set in this case
![image](https://cloud.githubusercontent.com/assets/2961943/16434334/1a12c8aa-3d59-11e6-9eda-aa5b574b649c.png)

**Comment by osvalr** [comment]
This module is working properly as expected, and it was a misuse from my part
Thanks @JulioSerna to help me solving it
