### ISSUE TITLE
[10][product_unique_serial] To separate the module product_unique_serial to add the last_location_id.

### ISSUE THREAD

**Issue by yaniaular** [Vauxoo/stock-logistics-workflow#24]
Introduction
----------------

The purpose of this issue is to separate the module product_unique_serial to add the **[last_location_id](https://github.com/Vauxoo/stock-logistics-workflow/blob/8.0/product_unique_serial/model/stock.py#L25-L43)** field in the **stock.production.lot** model in this repo of **Vauxoo/stock-logistic-workflow** version **10.0**

Why just last_location_id field and not all code?
------------------------------------------------------------------

In Odoo 10  there is a new field called **tracking** in the model of product.product, this field allows
(with the value 'serial') tracking serial numbers into unique per product.

That it was the main objetive of the product_unique_serial module.

This functionality there was not present in Odoo 8.0 but in Odoo 10 was integrated

The last_location_id is requested in yoytec project to filter just the serials with last_location_id with False value

**Comment by yaniaular** [comment]
@moylop260 @JulioSerna What do you think?

**Comment by moylop260** [comment]
+1
The module should be called different
@nhomar what name is ok for you?

**Comment by yaniaular** [comment]
@moylop260 @nhomar **stock_production_lot_last_location**  ?

**Comment by yaniaular** [comment]
@moylop260 @nhomar do you can help me to create the branch version 10 in [stock-logistic-workflow](https://github.com/Vauxoo/stock-logistics-workflow) repo?  Thanks!!

**Comment by moylop260** [comment]
Branch 10.0 created based on 8.0
https://github.com/Vauxoo/stock-logistics-workflow/tree/10.0
