### ISSUE TITLE
Need to have the 12.0 branch for this repo

### ISSUE THREAD

**Issue by ebirbe** [Vauxoo/stock-logistics-workflow#26]
I need the **12.0** branch of this repository. I need the module `stock_no_negative` in a 12.0 project. But I couldn't clone the branch when running the `clone_oca_dependencies` script:

```
INFO:root:* processing stock-logistics-workflow
INFO:root:Calling git clone -q git@github.com:Vauxoo/stock-logistics-workflow.git -b 12.0 /home/odoo/stock-logistics-workflow
fatal: Remote branch 12.0 not found in upstream origin
Traceback (most recent call last):
  File "./maintainer-quality-tools/travis/clone_oca_dependencies", line 124, in <module>
    run(home, build_dir)
  File "./maintainer-quality-tools/travis/clone_oca_dependencies", line 100, in run
    checkout_dir = git_checkout(home, depname, url, branch)
  File "./maintainer-quality-tools/travis/clone_oca_dependencies", line 71, in git_checkout
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '-q', 'git@github.com:Vauxoo/stock-logistics-workflow.git', '-b', '12.0', '/home/odoo/stock-logistics-workflow']' returned non-zero exit status 128
```

/cc @moylop260 @nhomar

**Comment by ebirbe** [comment]
I also need this other repository updated to the 12.0 branch:

https://github.com/vauxoo/account-closing/tree/12.0

Currently it has the branch, but with no modules inside. I need the `account_multicurrency_revaluation` module, but I can't open issues there.

Could you help me with that too, please?

**Comment by moylop260** [comment]
Are you not confused with 11.0 branch?
I mean, I saw the module in OCA just for this branch:
https://github.com/oca/account-closing/tree/11.0/account_multicurrency_revaluation

But there is not for 12.0 branch
This is a WIP from: https://github.com/OCA/account-closing/pull/88

FYI I just updated the branches but this was updated.
